<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>qsharp</string>
    <key>scopeName</key>
    <string>source.qsharp</string>
    <key>fileTypes</key>
    <array>
      <string>qs</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#attributes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#namespace-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import-export-directive</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#new-expression</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#struct-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#member-access</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#tuple-binding</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#library-invocation</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#library</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operations</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#literals</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#callable-invocation</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#callable-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#udt-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#array-creation-expression</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#local-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#array-assignment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#local-assignment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#quantum-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#if-statement</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#parenthesized-expression</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#expression-operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#identifier</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#boolean-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#result-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#pauli-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numeric-literal</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(^\s+)?(?=//)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.qsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.block.documentation.qsharp</string>
                <key>begin</key>
                <string>(?&lt;!/)///(?!/)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.qsharp</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=$)</string>
              </dict>
              <dict>
                <key>name</key>
                <string>comment.line.double-slash.qsharp</string>
                <key>begin</key>
                <string>(?&lt;!/)//(?:(?!/))</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.qsharp</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=$)</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.qsharp</string>
            <key>match</key>
            <string>\b(elif|else|repeat|until|fixup|for|in|while|return|fail|within|apply)\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>legacy allocation keywords (QDK &lt;1.0)</string>
            <key>name</key>
            <string>keyword.other.qsharp</string>
            <key>match</key>
            <string>\b(using|borrowing)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.qsharp</string>
            <key>match</key>
            <string>\b(new)\b</string>
          </dict>
        </array>
      </dict>
      <key>operations</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.other.qsharp</string>
            <key>match</key>
            <string>\b(as|internal|body|(a|A)djoint|(c|C)ontrolled|self|auto|distribute|invert|intrinsic|is)\b</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type-parameter</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.qsharp</string>
            <key>match</key>
            <string>\b(Int|BigInt|Double|Bool|Qubit|Pauli|Result|Range|String|Unit|Ctl|Adj)\b</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type-array-suffix</string>
          </dict>
        </array>
      </dict>
      <key>type-parameter</key>
      <dict>
        <key>name</key>
        <string>entity.name.type.type-parameter.qsharp</string>
        <key>match</key>
        <string>'[_[:alpha:]][_[:alnum:]]*</string>
      </dict>
      <key>library</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>support.function.quantum.qsharp</string>
            <key>match</key>
            <string>\b(CCNOT|CNOT|CX|CY|CZ|SWAP|SX|H|S|T|I|X|Y|Z|Rxx|Ryy|Rzz|Rx|Ry|Rz|R1Frac|R1|RFrac|R|ExpFrac|Exp|MResetEachZ|MResetX|MResetY|MResetZ|MeasureEachZ|MeasureAllZ|Measure|M|ResetAll|Reset)\b</string>
          </dict>
        </array>
      </dict>
      <key>library-invocation</key>
      <dict>
        <key>begin</key>
        <string>(?x)
\b(CCNOT|CNOT|CX|CY|CZ|SWAP|SX|H|S|T|I|X|Y|Z|Rxx|Ryy|Rzz|Rx|Ry|Rz|R1Frac|R1|RFrac|R|ExpFrac|Exp|MResetEachZ|MResetX|MResetY|MResetZ|MeasureEachZ|MeasureAllZ|Measure|M|ResetAll|Reset)\b\s*
(?=\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.quantum.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#argument-list</string>
          </dict>
        </array>
      </dict>
      <key>parenthesized-expression</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.open.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.close.qsharp</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-comma</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double.interpolated.qsharp</string>
            <key>begin</key>
            <string>\$"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.qsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.qsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.qsharp</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
              <dict>
                <key>name</key>
                <string>meta.interpolation.qsharp</string>
                <key>begin</key>
                <string>\{</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.section.interpolation.begin.qsharp</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\}</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.section.interpolation.end.qsharp</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#expression</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.double.qsharp</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.qsharp</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>namespace-declaration</key>
      <dict>
        <key>begin</key>
        <string>\b(namespace)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.namespace.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.name.type.namespace.qsharp</string>
            <key>match</key>
            <string>[_[:alpha:]][_[:alnum:]]*</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-accessor</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.curlybrace.open.qsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.curlybrace.close.qsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attributes</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#import-export-directive</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#new-expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#struct-declaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#member-access</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tuple-binding</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#library-invocation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#library</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#operations</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#literals</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#callable-invocation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#callable-declaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#udt-declaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#open-directive</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#array-creation-expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#local-declaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#array-assignment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#local-assignment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#quantum-declaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#if-statement</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#parenthesized-expression</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression-operators</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#identifier</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>callable-invocation</key>
      <dict>
        <key>begin</key>
        <string>(?x)
(?:(\:\:)\s*)?                                      # preceding member access
(?!(?:let|mutable|set|use|borrow|new|fixup|for|in|while|repeat|until|return|fail|within|apply|if|elif|else|not|and|or|namespace|import|export|open|operation|function|struct|newtype|internal|is)\b)
([_[:alpha:]][_[:alnum:]]*)\s*                      # callable name (not a keyword)
(?&lt;type_args&gt;\s*&lt;([^&lt;&gt;]|\g&lt;type_args&gt;)+&gt;\s*)?\s*    # type arguments
(?=\()                                              # open parentheses of argument list</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.accessor.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.qsharp</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-parameter-list</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#argument-list</string>
          </dict>
        </array>
      </dict>
      <key>callable-declaration</key>
      <dict>
        <key>begin</key>
        <string>(?x)
\b(operation|function)\b\s+
([_[:alpha:]][_[:alnum:]]*)\s*                      # callable name
(?&lt;type_args&gt;\s*&lt;([^&lt;&gt;]|\g&lt;type_args&gt;)+&gt;\s*)?\s*    # type arguments
(?=\()                                              # open parentheses of argument list</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.callable.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.qsharp</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type-parameter-list</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#parameter-list</string>
          </dict>
        </array>
      </dict>
      <key>type-parameter-list</key>
      <dict>
        <key>begin</key>
        <string>\&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.typeparameters.begin.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.typeparameters.end.qsharp</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>('[_[:alpha:]][_[:alnum:]]*)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.type-parameter.qsharp</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.separator.colon.qsharp</string>
            <key>match</key>
            <string>:</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.qsharp</string>
            <key>match</key>
            <string>\+</string>
          </dict>
          <dict>
            <key>name</key>
            <string>support.type.constraint.qsharp</string>
            <key>match</key>
            <string>\b(Eq|Add|Sub|Mul|Div|Mod|Signed|Ord|Show|Integral|Exp)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.squarebracket.open.qsharp</string>
            <key>match</key>
            <string>\[</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.squarebracket.close.qsharp</string>
            <key>match</key>
            <string>\]</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-comma</string>
          </dict>
        </array>
      </dict>
      <key>argument-list</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.open.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.close.qsharp</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#argument</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-comma</string>
          </dict>
        </array>
      </dict>
      <key>parameter-list</key>
      <dict>
        <key>begin</key>
        <string>(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.open.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\))</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.parenthesis.close.qsharp</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#parameter</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-comma</string>
          </dict>
        </array>
      </dict>
      <key>punctuation-comma</key>
      <dict>
        <key>name</key>
        <string>punctuation.separator.comma.qsharp</string>
        <key>match</key>
        <string>,</string>
      </dict>
      <key>identifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>([_[:alpha:]][_[:alnum:]]*)(\!*)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.readwrite.qsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.unwrap.qsharp</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>argument</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>parameter</key>
      <dict>
        <key>begin</key>
        <string>([_[:alpha:]][_[:alnum:]]*)\s*(:)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.variable.parameter.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.colon.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=(,|\)|\]))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#library</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression-operators</string>
          </dict>
        </array>
      </dict>
      <key>type-array-suffix</key>
      <dict>
        <key>begin</key>
        <string>\b\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.squarebracket.open.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.squarebracket.close.qsharp</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#punctuation-comma</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>udt-declaration</key>
      <dict>
        <key>begin</key>
        <string>(?=\bnewtype\b)</string>
        <key>end</key>
        <string>(?&lt;=\)|;)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?x)
(newtype)\b\s+
([_[:alpha:]][_[:alnum:]]*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.udt.qsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.udt.qsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\s*=)</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?:\s*=\s*)(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.parenthesis.open.qsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.parenthesis.close.qsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#literals</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation-comma</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#library</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?:\s*=\s*)</string>
            <key>end</key>
            <string>(?=;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#literals</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation-comma</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#library</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>struct-declaration</key>
      <dict>
        <key>begin</key>
        <string>(?x)
\b(struct)\b\s+
([_[:alpha:]][_[:alnum:]]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.struct.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.struct.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.curlybrace.open.qsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.curlybrace.close.qsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#struct-field</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation-comma</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#library</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>struct-field</key>
      <dict>
        <key>begin</key>
        <string>([_[:alpha:]][_[:alnum:]]*)\s*(:)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.separator.colon.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=(,|\}))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#type-parameter</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#library</string>
          </dict>
        </array>
      </dict>
      <key>new-expression</key>
      <dict>
        <key>begin</key>
        <string>(?x)
\b(new)\b\s+
([_[:alpha:]][_[:alnum:]]*)\s*
(?=\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.new.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.struct.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.curlybrace.open.qsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.curlybrace.close.qsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#spread-operator</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#field-initializer</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation-comma</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>field-initializer</key>
      <dict>
        <key>begin</key>
        <string>([_[:alpha:]][_[:alnum:]]*)\s*(=)(?![=&gt;])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=(,|\}))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>spread-operator</key>
      <dict>
        <key>name</key>
        <string>keyword.operator.spread.qsharp</string>
        <key>match</key>
        <string>\.\.\.</string>
      </dict>
      <key>statements</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attributes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#import-export-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#open-directive</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#new-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#struct-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#member-access</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tuple-binding</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#library-invocation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#library</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operations</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#callable-invocation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#callable-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#udt-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#array-creation-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#local-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#array-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#local-assignment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#quantum-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#if-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parenthesized-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression-operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#if-statement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#new-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#member-access</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#library-invocation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#callable-invocation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#library</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parenthesized-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#array-creation-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression-operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
      <key>member-access</key>
      <dict>
        <key>match</key>
        <string>(?x)
(\.)\s*
([_[:alpha:]][_[:alnum:]]*)\b
(?!\s*\()</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.accessor.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.qsharp</string>
          </dict>
        </dict>
      </dict>
      <key>attributes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(@)([_[:alpha:]][_[:alnum:]]*)\s*(?=\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.attribute.qsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.attribute.qsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#argument-list</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>(@)([_[:alpha:]][_[:alnum:]]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.attribute.qsharp</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.attribute.qsharp</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>import-export-directive</key>
      <dict>
        <key>begin</key>
        <string>\b(import|export)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.import.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=;)|$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(as)\b\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.qsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=(,|;)|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>entity.name.type.alias.qsharp</string>
                <key>match</key>
                <string>[_[:alpha:]][_[:alnum:]]*</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.wildcard.qsharp</string>
            <key>match</key>
            <string>\*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.namespace.qsharp</string>
            <key>match</key>
            <string>[_[:alpha:]][_[:alnum:]]*</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-accessor</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-comma</string>
          </dict>
        </array>
      </dict>
      <key>boolean-literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.true.qsharp</string>
            <key>match</key>
            <string>(?&lt;!\.)\btrue\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.false.qsharp</string>
            <key>match</key>
            <string>(?&lt;!\.)\bfalse\b</string>
          </dict>
        </array>
      </dict>
      <key>result-literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.result.zero.qsharp</string>
            <key>match</key>
            <string>(?&lt;!\.)\bZero\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.result.one.qsharp</string>
            <key>match</key>
            <string>(?&lt;!\.)\bOne\b</string>
          </dict>
        </array>
      </dict>
      <key>pauli-literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.pauli.qsharp</string>
            <key>match</key>
            <string>\b(Pauli(I|X|Y|Z))\b</string>
          </dict>
        </array>
      </dict>
      <key>punctuation-accessor</key>
      <dict>
        <key>name</key>
        <string>punctuation.accessor.qsharp</string>
        <key>match</key>
        <string>\.</string>
      </dict>
      <key>open-directive</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(open)\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.open.qsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>\b(as)\s+(?&lt;alias&gt;[_[:alpha:]][_[:alnum:]]*)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.alias.qsharp</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.alias.qsharp</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=;)</string>
              </dict>
              <dict>
                <key>name</key>
                <string>entity.name.type.namespace.qsharp</string>
                <key>match</key>
                <string>[_[:alpha:]][_[:alnum:]]*</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#punctuation-accessor</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>numeric-literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.hexadecimal.qsharp</string>
            <key>match</key>
            <string>\b0[xX][0-9a-fA-F][0-9a-fA-F_]*[lL]?\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.binary.qsharp</string>
            <key>match</key>
            <string>\b0[bB][01][01_]*[lL]?\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.octal.qsharp</string>
            <key>match</key>
            <string>\b0[oO][0-7][0-7_]*[lL]?\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.decimal.qsharp</string>
            <key>match</key>
            <string>(?x)
\b\d[\d_]* \. \d[\d_]* (?:[eE][+-]?\d+)?    # 1.0   3.14   1.0e-3
| \b\d[\d_]* [eE][+-]?\d+                    # 1e10
| \b\d[\d_]* [lL]?                           # 42   42L   1_000</string>
          </dict>
        </array>
      </dict>
      <key>array-creation-expression</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\w)\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.squarebracket.open.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.squarebracket.close.qsharp</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(size)\s*(?=\=)</string>
            <key>end</key>
            <string>(?=\])</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.size.qsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#argument</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#punctuation-comma</string>
          </dict>
        </array>
      </dict>
      <key>local-declaration</key>
      <dict>
        <key>begin</key>
        <string>(?x)
(?:\b(?:(let)|(mutable))\b\s*)
([_[:alpha:]][_[:alnum:]]*)\b\s*
(?=;|=|\))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.let.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.mutable.qsharp</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.variable.local.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=;|\))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#variable-initializer</string>
          </dict>
        </array>
      </dict>
      <key>tuple-binding</key>
      <dict>
        <key>match</key>
        <string>\b(let|mutable|set)\b(?=\s*\()</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.qsharp</string>
          </dict>
        </dict>
      </dict>
      <key>array-assignment</key>
      <dict>
        <key>begin</key>
        <string>(?x)
(?:\b(set)\b\s*)
([_[:alpha:]][_[:alnum:]]*)\b\s*
(?:(=)\s*([_[:alpha:]][_[:alnum:]]*)\b\s*(w\/)\s*|\b(w\/=)\s*)?
(\d+)\s*
(&lt;-)\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.set.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.variable.local.qsharp</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.qsharp</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.variable.local.qsharp</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.qsharp</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.qsharp</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.decimal.qsharp</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=;|\))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#callable-invocation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
      <key>local-assignment</key>
      <dict>
        <key>begin</key>
        <string>(?x)
(?:\b(set)\b\s*)
([_[:alpha:]][_[:alnum:]]*)\b\s*
(?=;|\+=|-=|=|\))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.set.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.variable.local.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=;|\))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#variable-initializer</string>
          </dict>
        </array>
      </dict>
      <key>variable-initializer</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!=|!)(?:(\+=)|(-=)|(=)|(&lt;-))(?!=|&gt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.increment.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.decrement.qsharp</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=[,\)\];}])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>if-statement</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!\.)\b(if)\b\s*(?=\S)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.if.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})(?!\s*\b(?:elif|else)\b)|(?=;)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.qsharp</string>
            <key>match</key>
            <string>\b(elif|else)\b</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.curlybrace.open.qsharp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.curlybrace.close.qsharp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#statements</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>expression-operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.logical.qsharp</string>
            <key>match</key>
            <string>\b(not|and|or)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.lambda.qsharp</string>
            <key>match</key>
            <string>(-&gt;|=&gt;)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.compound.qsharp</string>
            <key>match</key>
            <string>(\+=|-=|\*=|/=|%=|\^=|&amp;&amp;&amp;=|\|\|\|=|\^\^\^=|&lt;&lt;&lt;=|&gt;&gt;&gt;=|\bw/=)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.copy-update.qsharp</string>
            <key>match</key>
            <string>(\bw/|&lt;-)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.qsharp</string>
            <key>match</key>
            <string>(?&lt;![=&lt;&gt;!+\-*/%^&amp;|~])=(?![=&gt;])</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.range.qsharp</string>
            <key>match</key>
            <string>(\.\.\.|\.\.)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.bitwise.qsharp</string>
            <key>match</key>
            <string>(&amp;&amp;&amp;|\|\|\||\^\^\^|~~~|&lt;&lt;&lt;|&gt;&gt;&gt;)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.comparison.qsharp</string>
            <key>match</key>
            <string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.arithmetic.qsharp</string>
            <key>match</key>
            <string>(\+|\-|\*|/|%|\^)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.ternary.qsharp</string>
            <key>match</key>
            <string>(\?|\|)</string>
          </dict>
        </array>
      </dict>
      <key>quantum-declaration</key>
      <dict>
        <key>begin</key>
        <string>(?x)
(?:\b(?:(use)|(borrow))\b\s*)
([_[:alpha:]][_[:alnum:]]*)\b\s*
(?=;|=|\))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.use.qsharp</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.borrow.qsharp</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.variable.local.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=;|\))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#quantum-initializer</string>
          </dict>
        </array>
      </dict>
      <key>quantum-initializer</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;!=|!)(=)(?!=|&gt;)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.qsharp</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=[,\)\];}])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>